language: python
python:
  - 3.5
install:
  - pip3 install codecov
  - pip3 install cov cov-report
script:
  - ./setup.py test
after_success:
  - codecov
before_install:
  - chmod a+x setup.py
